version: 2

builds:
  - id: goclaw
    binary: goclaw
    main: .
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    # Name your archive with a sensible pattern, including the project name, OS, and architecture.
    # The .Format directive is already used by goreleaser so no need to specify it.
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"

checksum:
  name_template: 'checksums.txt'

release:
  # You can customize this if you want to upload to a different repository.
  # repo:
  #   owner: your_github_username
  #   name: your_repo_name
  # This allows GoReleaser to create a GitHub release.
  # If you are not using GitHub, you might need to adjust or disable this section.
  disable: false # Set to true if you don't want to create a GitHub release
